#!/usr/bin/env node

import { knowledgeEngine } from '../src/knowledge/engine.js';

const PROJECT_ID = 'cavalry-2.7.2-golden-corpus';
const failures = [
  {
    intent: 'Build and verify golden scene 04-word-rise-stagger',
    approach: 'Use the high-level word animation helper.',
    mcpOperation: 'text_animate_words', category: 'LIVE_CORPUS_VALIDATION',
    error: '04-word-rise-stagger: missing node type stagger',
    cause: 'The helper completed without producing the required Stagger node in Cavalry 2.7.2.',
    solution: 'Create Sub-Mesh and Stagger explicitly, connect Stagger to shapeTimeOffset, and validate the saved graph.',
    verifiedReplacement: 'Golden scene 04-word-rise-stagger passed graph extraction and five-frame visual validation.',
  },
  {
    intent: 'Build and verify golden scene 15-svg-asset-footage',
    approach: 'Assume the imported asset node is reported as fileAsset.',
    mcpOperation: 'asset_import', category: 'LIVE_CORPUS_VALIDATION',
    error: '15-svg-asset-footage: missing node type fileAsset',
    cause: 'Cavalry 2.7.2 reports the imported SVG graph as asset plus svgShape.',
    solution: 'Validate against the actual runtime node types asset and svgShape.',
    verifiedReplacement: 'Golden scene 15-svg-asset-footage passed with asset and svgShape nodes.',
  },
  {
    intent: 'Validate recipe repeated-data-cards in live Cavalry',
    approach: 'Render five timing checkpoints from the initial card grid.',
    mcpOperation: 'preview_frame', category: 'LIVE_RECIPE_VALIDATION',
    error: 'repeated-data-cards produced no visible motion across validation frames',
    cause: 'The initial card source had no animated property and default grid spacing caused overlap.',
    solution: 'Animate source opacity and explicitly set Grid Distribution count and size.',
    verifiedReplacement: 'Corrected repeated-data-cards produced three distinct rendered states and a visible repeated grid.',
  },
  {
    intent: 'Build and verify golden scene 14-editable-svg-path',
    approach: 'Convert an SVG staged outside configured filesystem roots.',
    mcpOperation: 'svg_convert_to_layers', category: 'LIVE_CORPUS_VALIDATION',
    error: "Access to filesystem path '/tmp/cavalry-golden-editable.svg' is outside the authorized sandbox roots.",
    cause: 'On macOS, /tmp and /private/tmp path canonicalization differed during path authorization.',
    solution: 'Stage through os.tmpdir() and pass the canonical returned path.',
    verifiedReplacement: 'Golden scene 14-editable-svg-path converted, saved, rendered, and passed graph validation.',
  },
  {
    intent: 'Validate recipe procedural-burst in live Cavalry',
    approach: 'Animate only source scale.y through a Duplicator.',
    mcpOperation: 'preview_frame', category: 'LIVE_RECIPE_VALIDATION',
    error: 'procedural-burst produced no visible motion across validation frames',
    cause: 'The valid source scale curve did not change the duplicated rendered outcome in this graph.',
    solution: 'Retain the scale curve and add a verified shared opacity driver that propagates to duplicates.',
    verifiedReplacement: 'Corrected procedural-burst produced three distinct rendered states.',
  },
  {
    intent: 'Build and verify golden scene 01-basic-transform-keyframes',
    approach: 'Keyframe basicShape rotation and assume success from the command response.',
    mcpOperation: 'keyframe_create', category: 'LIVE_CORPUS_VALIDATION',
    error: '01-basic-transform-keyframes: missing animated attribute rotation',
    cause: 'The rotation keyframe call returned without error but no rotation curve persisted in the scene graph.',
    solution: 'Verify curves from the saved snapshot and use persisted position, opacity, and scale attributes for the recipe.',
    verifiedReplacement: 'Golden scene 01 passed extracted-curve checks and five-frame render validation.',
  },
  {
    intent: 'Build and verify golden scene 20-logo-geometric-assembly',
    approach: 'Create a triangle primitive directly.',
    mcpOperation: 'layer_create_primitive', category: 'LIVE_CORPUS_VALIDATION',
    error: "Cannot read properties of null (reading 'uuid')",
    cause: 'triangle is not a supported primitive identifier in the live Cavalry 2.7.2 runtime.',
    solution: 'Use polygon primitives for geometric logo parts.',
    verifiedReplacement: 'Golden scene 20 built with polygons and passed hierarchy, animation, and render checks.',
  },
  {
    intent: 'Validate recipe orbit-loop in live Cavalry',
    approach: 'Drive the orbit parent rotation with a default Oscillator.',
    mcpOperation: 'preview_frame', category: 'LIVE_RECIPE_VALIDATION',
    error: 'orbit-loop produced no visible motion across validation frames',
    cause: 'The default Oscillator connection was structurally valid but produced a static visible output.',
    solution: 'Use a closed five-key position loop and verify that first/last samples match while intermediate renders differ.',
    verifiedReplacement: 'Corrected orbit-loop produced four distinct rendered states with matching loop endpoints.',
  },
  {
    intent: 'Build and verify golden scene 14-editable-svg-path',
    approach: 'Convert an SVG directly from the workspace path.',
    mcpOperation: 'svg_convert_to_layers', category: 'LIVE_CORPUS_VALIDATION',
    error: "Bridge operation 'svg_convert_to_layers' timed out after 15000ms.",
    cause: 'The live converter hung on the workspace path but succeeded with a staged temporary input.',
    solution: 'Stage SVG input in os.tmpdir(), relaunch Cavalry after a converter hang, then validate the editableShape output.',
    verifiedReplacement: 'Golden scene 14 passed using the staged temporary SVG workflow.',
  },
  {
    intent: 'Run the complete live integration suite in one Cavalry process',
    approach: 'Execute all 22 stateful integration tests sequentially in one host session.',
    mcpOperation: 'integration_test_suite', category: 'LIVE_BRIDGE_VALIDATION',
    error: 'Cavalry terminated natively before the final test after the long combined sequence.',
    cause: 'The crash appeared after the long stateful sequence when callback-server cleanup and final-scene isolation were not deterministic; Crashpad captured the native failure.',
    solution: 'Forward the Node test context, stop the callback receiver in an after hook, and start the final end-to-end test from a forced blank scene.',
    verifiedReplacement: 'Tests 1–20 passed in sequence; after the native host exit, tests 21–22 both passed on a fresh Cavalry process, including the third-party plugin.',
  },
  {
    intent: 'Set visible Text Shape content through the bridge',
    approach: 'Set the text attribute to a plain string in a bulk attribute update.',
    mcpOperation: 'attribute_set_many', category: 'LIVE_TEXT_VALIDATION',
    error: 'The command succeeded but the rendered layer retained the default Cavalry text.',
    cause: 'Cavalry 2.7.2 expects the rich text payload shape for this attribute.',
    solution: 'Set text explicitly as { text, overrides: [] } after other attributes.',
    verifiedReplacement: 'Word, character, marker, mask, progress, and end-to-end text rendered with requested content.',
  },
  {
    intent: 'Create and sequence Camera Guides through the live bridge',
    approach: 'Create a Camera Guide, then exercise camera guide-array routes in the same host.',
    mcpOperation: 'camera_create_guide', category: 'LIVE_HOST_STABILITY',
    error: 'Camera Guide creation returned success, then Cavalry 2.7.2 exited before the next ordinary bridge request.',
    cause: 'The documented Camera Guide constructor enters an unstable native path in Cavalry 2.7.2.',
    solution: 'Treat Camera Guide creation and dependent add/remove/sequence routes as a precise 2.7.2 limitation; do not replay them in a shared validation process.',
    verifiedReplacement: 'Planar camera create/list/get-active/look-at routes passed live; guide-dependent routes remain quarantined.',
  },
  {
    intent: 'Change a live Planar Camera mode',
    approach: 'Invoke camera_set_type on a valid live planarCamera node.',
    mcpOperation: 'camera_set_type', category: 'LIVE_HOST_STABILITY',
    error: 'camera_set_type timed out after 15 seconds and Cavalry exited immediately afterward.',
    cause: 'The native camera mode mutation is unstable in Cavalry 2.7.2 even with a valid camera fixture.',
    solution: 'Create the camera with its intended type and avoid post-creation type mutation on 2.7.2.',
    verifiedReplacement: 'camera_create with cameraType plus camera_get_active, camera_list, and camera_look_at passed live.',
  },
  {
    intent: 'Create and resynchronise Editable Path keyframes',
    approach: 'Keyframe a valid editableShape path payload and call resyncPathKeyframes.',
    mcpOperation: 'path_keyframe_create', category: 'LIVE_HOST_STABILITY',
    error: 'Path keyframe creation/resynchronisation timed out and terminated Cavalry 2.7.2.',
    cause: 'api.keyframe plus api.resyncPathKeyframes is unstable for the live Editable Path fixture.',
    solution: 'Use static path editing plus ordinary transform animation; quarantine path keyframe set/resync/morph on 2.7.2.',
    verifiedReplacement: 'All static Editable Path inspection, contour, point, handle, selection, open/close, and set routes passed live.',
  },
  {
    intent: 'Continue MCP commands while the Cavalry timeline is playing',
    approach: 'Invoke timeline_play followed by timeline_stop and ordinary tool routes in the same bridge session.',
    mcpOperation: 'timeline_play', category: 'LIVE_BRIDGE_VALIDATION',
    error: 'timeline_play returned success, but timeline_stop and subsequent bridge requests timed out until Cavalry was restarted.',
    cause: 'The bridge event loop cannot service requests reliably while native playback is active in Cavalry 2.7.2.',
    solution: 'Avoid timeline_play in automated shared sessions; preview explicit frames instead, or isolate playback in a disposable host process.',
    verifiedReplacement: 'timeline_stop, tool state, and all transform routes passed on a clean non-playing host.',
  },
  {
    intent: 'Set codec-specific Render Manager generator attributes',
    approach: 'Write nested generator settings as a single object.',
    mcpOperation: 'render_item_set_generator', category: 'LIVE_RENDER_VALIDATION',
    error: 'Cavalry ignored nested generator fields and reported unchanged codec settings.',
    cause: 'Render format properties are flattened generator attributes in Cavalry 2.7.2.',
    solution: 'Flatten generator fields, write each native attribute, and read back every requested value.',
    verifiedReplacement: 'MP4 quality/audio settings passed live; HEVC audio returned a precise unsupported-attribute limitation.',
  },
  {
    intent: 'Inspect an embedded sRGB profile after repeated large-scene cycles',
    approach: 'Import and immediately inspect a 2048px sRGB PNG after multiple compatibility runs.',
    mcpOperation: 'asset_icc_profile', category: 'LIVE_COMPATIBILITY_VALIDATION',
    error: 'The embedded profile intermittently returned as an empty string in a long-lived host process.',
    cause: 'Cavalry asset metadata readiness becomes nondeterministic after repeated large-scene import/reset cycles.',
    solution: 'Reload the asset with bounded retries and run compatibility certification from a clean Cavalry process.',
    verifiedReplacement: 'A clean-process run returned sRGB IEC61966-2.1 and passed save/reopen plus rendered glyph validation.',
  },
  {
    intent: 'Animate an Editable Path without entering Cavalry 2.7.2 native path-keyframe code',
    approach: 'Use the native path keyframe and resynchronisation routes.',
    mcpOperation: 'path_animation_safe', category: 'LIVE_HOST_STABILITY',
    error: 'Native Editable Path keyframe and morph routes can terminate the host.',
    cause: 'Cavalry 2.7.2 is unstable when path topology is keyframed through api.keyframe/resyncPathKeyframes.',
    solution: 'Validate identical contour topology, sample the morph into bounded editableShape layers, animate their visibility, checkpoint before construction, and roll back on failure.',
    verifiedReplacement: 'path_animation_safe and path_morph_safe built, rendered, saved, and reopened a persistent sampled morph while the bridge remained healthy.',
  },
  {
    intent: 'Sequence camera views without unstable Camera Guide APIs',
    approach: 'Create Camera Guides and mutate a live Planar Camera type.',
    mcpOperation: 'camera_sequence_create', category: 'LIVE_HOST_STABILITY',
    error: 'Camera Guide creation and camera_set_type can time out or terminate Cavalry 2.7.2.',
    cause: 'The native Camera Guide and post-creation camera-mode mutation paths are host-unstable in this release.',
    solution: 'Create cameras with their final type and build explicit camera cut or transition keyframes with camera_cut, camera_transition, or camera_sequence_create.',
    verifiedReplacement: 'Camera cut and transition sequences persisted with verified keyframes and rendered previews.',
  },
  {
    intent: 'Preview timeline motion while preserving bridge responsiveness',
    approach: 'Start native timeline playback during an MCP session.',
    mcpOperation: 'timeline_preview_playback', category: 'LIVE_BRIDGE_VALIDATION',
    error: 'Native timeline playback blocks subsequent bridge requests until Cavalry is restarted.',
    cause: 'The bridge event loop is not reliably serviced while native playback runs in Cavalry 2.7.2.',
    solution: 'Render the requested frame interval to a temporary H.264 preview and inspect that deterministic artifact.',
    verifiedReplacement: 'timeline_preview_playback produced a playable MP4 and the bridge accepted subsequent requests.',
  },
  {
    intent: 'Deliver HEVC or ProRes video with audio',
    approach: 'Enable audio directly on the native HEVC or ProRes Render Manager generator.',
    mcpOperation: 'render_mux_audio', category: 'LIVE_RENDER_VALIDATION',
    error: 'Cavalry 2.7.2 does not expose a working audio export attribute for HEVC and ProRes generators.',
    cause: 'Those generator schemas omit native audio output in the tested host.',
    solution: 'Render video and audio separately, mux them with FFmpeg, and verify both streams with ffprobe.',
    verifiedReplacement: 'render_mux_audio produced an MP4 containing verified video and audio streams.',
  },
  {
    intent: 'Open and save project paths through macOS automation',
    approach: 'Drive Cavalry native file dialogs through Accessibility controls.',
    mcpOperation: 'dialog_open_file', category: 'UI_AUTOMATION_LIMITATION',
    error: 'Native dialog file-filter selection is nondeterministic under macOS Accessibility automation.',
    cause: 'Cavalry-owned file dialogs expose inconsistent focus and filtered-row selection state.',
    solution: 'Use scene_open, scene_save_as, and project_set for deterministic path operations; reserve dialog tools for supervised interactive use.',
    verifiedReplacement: 'Structured scene and project routes opened and saved the same paths with state readback.',
  },
  {
    intent: 'Control Cavalry UI-only commands from MCP',
    approach: 'Assume all menu, workspace, tag, preset, and custom plug-in UI state is scriptable.',
    mcpOperation: 'ui_driver_status', category: 'UI_AUTOMATION_LIMITATION',
    error: 'Several editor-only systems have no stable public API or deterministic Accessibility representation.',
    cause: 'Cavalry 2.7.2 exposes menu commands and preferences, but some custom editors and fixture-dependent panels do not expose semantic controls.',
    solution: 'Require CAVALRY_UI_DRIVER=true, use command/shortcut discovery for observable menu actions, and return PLATFORM_LIMITATION for unsupported editor-only mutations.',
    verifiedReplacement: 'Twelve stable UI operations passed live, including command execution, shortcuts, preferences, tool selection, workspace listing, window opening, and Focus Mode.',
  },
  {
    intent: 'Set Audio Shape timing and loudness attributes',
    approach: 'Write generic timeOffset and volume attribute names.',
    mcpOperation: 'audio_set_time_offset', category: 'LIVE_AUDIO_VALIDATION',
    error: 'Generic names did not map to the live Cavalry 2.7.2 Audio Shape schema.',
    cause: 'The runtime attributes are frameOffset and playbackVolume.',
    solution: 'Map MCP timeOffset to frameOffset and volume to playbackVolume, then read back the native values.',
    verifiedReplacement: 'All Audio Shape fixture routes passed with live state readback using a generated WAV asset.',
  },
];

for (const failure of failures) {
  await knowledgeEngine.addFailure(failure, 'project', PROJECT_ID, '2.7.2');
}
process.stdout.write(`${JSON.stringify({ recorded: failures.length }, null, 2)}\n`);
